##Array ceration  Function

In [8]:
import numpy as np

In [9]:
np.array([1,2,3])
print(

array([1, 2, 3])

In [ ]:
d=np.ones(

In [14]:
d=np.zeros((2,3),dtype=int)

In [16]:
f = np.eye(4)
print("identity materix f:\n",f)

identity materix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2 array manipulation

In [20]:
a1=np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("reshaped array",reshaped)

reshaped array [[1 2 3]]


In [26]:
f1 =np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [24]:
e1= np.array([[1,2],[3,4]])
transpond =np.transpose(e1)
print(e1)

[[1 2]
 [3 4]]


In [27]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked array:\n",stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [28]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked array:\n",stacked)

Stacked array:
 [1 2 3 4]



Mathematical Operation in num py

In [29]:
g=np.array([1,2,3,4,])
added =np.add(g,2)
print("added 2 amd g: ",added)

added 2 amd g:  [3 4 5 6]


In [32]:
sqrt_val =np.sqrt(g)
print("squre root of g:",sqrt_val)

squre root of g: [1.         1.41421356 1.73205081 2.        ]


In [34]:
power_val =np.power(g,2)
print("squre root of g:",power_val)

squre root of g: [ 1  4  9 16]


In [37]:
a=np.array([1,2,3])
g=np.array([1,2,3,4])
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [39]:
a3=np.array([1,2,3,])
dot_product =np.dot(a,g)
print("dot_product",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [43]:
a3=np.array([1,2,3])
dot_product =np.dot(a1,a)
print("dot productof a1 and a : ",dot_product)

dot productof a1 and a :  14



Satastics Function in num py

In [61]:
s=np.array([1,2,3,4])
mean =np.mean(s)
print("Menimum of s",mean)

Menimum of s 2.5


In [53]:

var =np.var(s)
print("varience of s",var)

varience of s 1.25



std_dev =np.std(s)
print("standard deavition of s",std_dev)

In [60]:

max =np.max(s)
print("maximum value of s",max)

maximum value of s 4


In [57]:
s

array([1, 2, 3, 4])

In [58]:
avg =np.average(s)
print("average of s",avg)

average of s 2.5



Linear algebra 


Random Sampling


In [80]:
random_vals= np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.4236548  0.64589411 0.43758721]


In [81]:
random_int= np.random.randint(0,10,size=4)
print("Random values:",random_int)

Random values: [6 8 8 1]


In [94]:
np.random.seed(0)
rand_int= np.random.randint(0,10,size=5)
print("Random values:",rand_int)

Random values: [5 0 3 3 7]


Boolean & Logical Function


In [85]:
logical_test =np.array([True,False,True])
all_true =np