In [1]:
import numpy as np 

In [2]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [3]:
arr = np.array(my_list) 

In [4]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(20,10)

array([], dtype=int64)

In [8]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [9]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.zeros(5)  #PARAMETER TUNNING

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5, dtype=int)  #HYPERPARAMETER TUNNING 

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,2)) 

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((2,3), dtype = int) 

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.zeros((10, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(4) 

array([1., 1., 1., 1.])

In [18]:
np.ones((2,3), dtype=int) 

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.two((2,3)) 

AttributeError: module 'numpy' has no attribute 'two'

In [20]:
np.three((2,3)) 

AttributeError: module 'numpy' has no attribute 'three'

In [21]:
rand(2,3)

NameError: name 'rand' is not defined

In [22]:
random.rand(2,3)

NameError: name 'random' is not defined

In [34]:
np.random.rand(2)

array([0.81822895, 0.03543466])

In [44]:
np.random.rand(2, 3)  

array([[0.55585799, 0.09207481, 0.94220849],
       [0.34198824, 0.68470354, 0.5009294 ]])

In [51]:
np.random.randint(2)

1

In [59]:
np.random.randint(2,9) 

8

In [60]:
np.random.randint(2, 9, 4) 

array([4, 8, 3, 7], dtype=int32)

In [69]:
import numpy as np

def generate_otp(length=4):
    # Generate OTP of given length using np.random.randint
    otp = ''.join([str(np.random.randint(0, 10)) for _ in range(length)])
    return otp

# Example usage
print("Your OTP is:", generate_otp())

Your OTP is: 1550


In [70]:
np.random.randint(10,40,(10,10))  

array([[33, 37, 24, 25, 30, 27, 39, 13, 19, 32],
       [33, 36, 11, 29, 13, 34, 22, 36, 11, 36],
       [23, 28, 24, 32, 37, 18, 23, 20, 34, 34],
       [37, 31, 22, 11, 17, 15, 17, 13, 17, 32],
       [24, 18, 33, 10, 33, 24, 38, 20, 21, 18],
       [16, 31, 34, 29, 25, 30, 11, 22, 14, 11],
       [36, 39, 39, 23, 27, 28, 10, 29, 15, 18],
       [19, 28, 39, 14, 26, 13, 12, 18, 24, 20],
       [37, 12, 10, 28, 17, 24, 34, 10, 16, 20],
       [39, 21, 36, 10, 19, 30, 28, 24, 19, 26]], dtype=int32)

In [71]:
arr1 = np.random.randint(10,40,(10,10)) 
print(arr1)

[[26 26 14 37 30 36 25 23 26 27]
 [18 23 30 11 36 11 33 11 19 30]
 [28 36 13 26 11 26 26 37 15 19]
 [32 32 13 34 22 30 27 25 21 32]
 [34 11 22 33 38 26 32 24 21 14]
 [15 14 32 30 22 21 29 28 14 33]
 [14 22 22 38 28 17 30 31 32 30]
 [13 39 20 20 13 11 21 29 18 34]
 [33 12 15 36 24 25 12 20 27 37]
 [17 19 27 20 34 39 30 22 27 39]]


In [73]:
print(arr1) 

[[26 26 14 37 30 36 25 23 26 27]
 [18 23 30 11 36 11 33 11 19 30]
 [28 36 13 26 11 26 26 37 15 19]
 [32 32 13 34 22 30 27 25 21 32]
 [34 11 22 33 38 26 32 24 21 14]
 [15 14 32 30 22 21 29 28 14 33]
 [14 22 22 38 28 17 30 31 32 30]
 [13 39 20 20 13 11 21 29 18 34]
 [33 12 15 36 24 25 12 20 27 37]
 [17 19 27 20 34 39 30 22 27 39]]


In [74]:
arr1[5]

array([15, 14, 32, 30, 22, 21, 29, 28, 14, 33], dtype=int32)

In [76]:
arr2 = np.random.randint(2, 9,(5,7)) 
print(arr2)

[[3 3 7 8 2 6 7]
 [2 5 6 5 2 3 6]
 [2 4 8 8 5 6 4]
 [7 2 6 3 6 3 6]
 [6 3 3 3 6 5 3]]


In [77]:
arr2[-3] 

array([2, 4, 8, 8, 5, 6, 4], dtype=int32)

In [78]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [79]:
arr2[2:10] 

array([[2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [80]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [81]:
arr2[:] 

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [82]:
arr2[::-1]  

array([[6, 3, 3, 3, 6, 5, 3],
       [7, 2, 6, 3, 6, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [2, 5, 6, 5, 2, 3, 6],
       [3, 3, 7, 8, 2, 6, 7]], dtype=int32)

In [83]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [84]:
arr2[::3] 

array([[3, 3, 7, 8, 2, 6, 7],
       [7, 2, 6, 3, 6, 3, 6]], dtype=int32)

In [85]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [86]:
arr2[3,4] 

np.int32(6)

In [90]:
print(arr2[3,4])

6


In [92]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [93]:
print(arr2[-4, -5]) 

6


In [94]:
arr2

array([[3, 3, 7, 8, 2, 6, 7],
       [2, 5, 6, 5, 2, 3, 6],
       [2, 4, 8, 8, 5, 6, 4],
       [7, 2, 6, 3, 6, 3, 6],
       [6, 3, 3, 3, 6, 5, 3]], dtype=int32)

In [95]:
arr2[0, 1] = 10

In [96]:
arr2

array([[ 3, 10,  7,  8,  2,  6,  7],
       [ 2,  5,  6,  5,  2,  3,  6],
       [ 2,  4,  8,  8,  5,  6,  4],
       [ 7,  2,  6,  3,  6,  3,  6],
       [ 6,  3,  3,  3,  6,  5,  3]], dtype=int32)

In [98]:
arr2[:, 0]

array([3, 2, 2, 7, 6], dtype=int32)

In [99]:
arr2[:, -3]

array([2, 2, 5, 6, 6], dtype=int32)

In [100]:
arr2

array([[ 3, 10,  7,  8,  2,  6,  7],
       [ 2,  5,  6,  5,  2,  3,  6],
       [ 2,  4,  8,  8,  5,  6,  4],
       [ 7,  2,  6,  3,  6,  3,  6],
       [ 6,  3,  3,  3,  6,  5,  3]], dtype=int32)

In [101]:
arr2[2:5, 2:5] 

array([[8, 8, 5],
       [6, 3, 6],
       [3, 3, 6]], dtype=int32)

In [102]:
arr2

array([[ 3, 10,  7,  8,  2,  6,  7],
       [ 2,  5,  6,  5,  2,  3,  6],
       [ 2,  4,  8,  8,  5,  6,  4],
       [ 7,  2,  6,  3,  6,  3,  6],
       [ 6,  3,  3,  3,  6,  5,  3]], dtype=int32)

In [103]:
arr2[1:4, 2:4]

array([[6, 5],
       [8, 8],
       [6, 3]], dtype=int32)

In [104]:
# masking or filter in numpy 

In [105]:
arr2

array([[ 3, 10,  7,  8,  2,  6,  7],
       [ 2,  5,  6,  5,  2,  3,  6],
       [ 2,  4,  8,  8,  5,  6,  4],
       [ 7,  2,  6,  3,  6,  3,  6],
       [ 6,  3,  3,  3,  6,  5,  3]], dtype=int32)

In [106]:
arr2 > 5 

array([[False,  True,  True,  True, False,  True,  True],
       [False, False,  True, False, False, False,  True],
       [False, False,  True,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [ True, False, False, False,  True, False, False]])

In [107]:
arr2[arr2 > 5] 

array([10,  7,  8,  6,  7,  6,  6,  8,  8,  6,  7,  6,  6,  6,  6,  6],
      dtype=int32)

In [108]:
arr2[arr2 >= 5] 

array([10,  7,  8,  6,  7,  5,  6,  5,  6,  8,  8,  5,  6,  7,  6,  6,  6,
        6,  6,  5], dtype=int32)

In [109]:
arr2

array([[ 3, 10,  7,  8,  2,  6,  7],
       [ 2,  5,  6,  5,  2,  3,  6],
       [ 2,  4,  8,  8,  5,  6,  4],
       [ 7,  2,  6,  3,  6,  3,  6],
       [ 6,  3,  3,  3,  6,  5,  3]], dtype=int32)

In [110]:
arr2[arr2 == 5] 

array([5, 5, 5, 5], dtype=int32)

In [111]:
arr2[arr2 != 5] 

array([ 3, 10,  7,  8,  2,  6,  7,  2,  6,  2,  3,  6,  2,  4,  8,  8,  6,
        4,  7,  2,  6,  3,  6,  3,  6,  6,  3,  3,  3,  6,  3],
      dtype=int32)

In [112]:
arr

array([0, 1, 2, 3, 4, 5])

In [113]:
arr.reshape(2,3) 

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:
arr.reshape(4,3)  

ValueError: cannot reshape array of size 6 into shape (4,3)

In [120]:
arr.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [121]:
arr

array([0, 1, 2, 3, 4, 5])

In [122]:
arr.max()

np.int64(5)

In [123]:
arr.min()

np.int64(0)